/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package sageniuz

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val s = MyService()
    s.print(App().greeting)
}
